/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsIndexImport } from './routes/docs/index'
import { Route as DocsApiurlImport } from './routes/docs/$api_url'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DocsIndexRoute = DocsIndexImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRoute,
} as any)

const DocsApiurlRoute = DocsApiurlImport.update({
  id: '/docs/$api_url',
  path: '/docs/$api_url',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/docs/$api_url': {
      id: '/docs/$api_url'
      path: '/docs/$api_url'
      fullPath: '/docs/$api_url'
      preLoaderRoute: typeof DocsApiurlImport
      parentRoute: typeof rootRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/docs/$api_url': typeof DocsApiurlRoute
  '/docs': typeof DocsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/docs/$api_url': typeof DocsApiurlRoute
  '/docs': typeof DocsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/docs/$api_url': typeof DocsApiurlRoute
  '/docs/': typeof DocsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/$api_url' | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$api_url' | '/docs'
  id: '__root__' | '/' | '/docs/$api_url' | '/docs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DocsApiurlRoute: typeof DocsApiurlRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DocsApiurlRoute: DocsApiurlRoute,
  DocsIndexRoute: DocsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/docs/$api_url",
        "/docs/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/docs/$api_url": {
      "filePath": "docs/$api_url.tsx"
    },
    "/docs/": {
      "filePath": "docs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
